
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JLayeredPane;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abdullah Hadi
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountType = new javax.swing.ButtonGroup();
        PenerimaType = new javax.swing.ButtonGroup();
        PenerimaTypeUpdate = new javax.swing.ButtonGroup();
        Verifikasi = new javax.swing.ButtonGroup();
        jLayeredMain = new javax.swing.JLayeredPane();
        pLogin = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        pfPassword = new javax.swing.JPasswordField();
        pRegistrasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNewRegister = new javax.swing.JButton();
        btnCancelRegis = new javax.swing.JButton();
        tfRegisName = new javax.swing.JTextField();
        tfRegisUsername = new javax.swing.JTextField();
        tfRegisEmail = new javax.swing.JTextField();
        tfRegisPassword = new javax.swing.JTextField();
        tfRegisPasswordConfirmation = new javax.swing.JTextField();
        rbRegisDonatur = new javax.swing.JRadioButton();
        rbRegisPengalangDana = new javax.swing.JRadioButton();
        tfRegisTelp = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        pMain = new javax.swing.JPanel();
        pUserinfo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEditProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pUserMain = new javax.swing.JPanel();
        pMainGalangDana = new javax.swing.JPanel();
        pMainPengalangDana = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEventPD = new javax.swing.JList<>();
        btnAddEvent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDeskripsiPD = new javax.swing.JTextArea();
        btnUpdateEvent = new javax.swing.JButton();
        btnDeleteEvent = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        pEventCreate = new javax.swing.JPanel();
        tfNamaPenerimaCreate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfAlamatPenerimaCreate = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNamaEventCreate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfTanggalMulaiCreate = new javax.swing.JTextField();
        tfTanggalSelesaiCreate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfTargetDanaCreate = new javax.swing.JTextField();
        tfDescriptionCreate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rbPersonal = new javax.swing.JRadioButton();
        rbLembaga = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        btnDoneCreateEvent = new javax.swing.JButton();
        btnCancelCreateEvent = new javax.swing.JButton();
        pEventUpdate = new javax.swing.JPanel();
        tfNamaPenerimaUpdate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfAlamatPenerimaUpdate = new javax.swing.JTextField();
        tfTelpPenerimaUpdate = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfNamaEventUpdate = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfTanggalMulaiUpdate = new javax.swing.JTextField();
        tfTanggalSelesaiUpdate = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfTargetDanaUpdate = new javax.swing.JTextField();
        tfDescriptionUpdate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rbPersonalUpdate = new javax.swing.JRadioButton();
        rbLembagaUpdate = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        btnDoneUpdateEvent = new javax.swing.JButton();
        btnCancelUpdateEvent = new javax.swing.JButton();
        pMainDonatur = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEventDNT = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDeskripsiDNT = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        pPilihanDonatur = new javax.swing.JPanel();
        pBelumDonasi = new javax.swing.JPanel();
        btnMauDonasi = new javax.swing.JButton();
        pDonasiPertama = new javax.swing.JPanel();
        tfNominalPertama = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btnKirimDonasi = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        pIdlePilihanDonasi = new javax.swing.JPanel();
        tfIdleNominal = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnUpdateDonasi = new javax.swing.JButton();
        btnBatalDonasi = new javax.swing.JButton();
        pEditUser = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tfNewName = new javax.swing.JTextField();
        tfNewNoTelp = new javax.swing.JTextField();
        tfNewEmail = new javax.swing.JTextField();
        btnDoneEditProf = new javax.swing.JButton();
        btnCancelEditProf = new javax.swing.JButton();
        pAdmin = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        btnLogOutAdmin = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pVerfikasi = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listEventAdmin = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        taDeskripsiEventAdmin = new javax.swing.JTextArea();
        jLabel41 = new javax.swing.JLabel();
        rbVerifTrue = new javax.swing.JRadioButton();
        rbVarifFalse = new javax.swing.JRadioButton();
        pViewDnt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDeskripsiDtnInAdmin = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        listDntInAdmin = new javax.swing.JList<>();
        pViewPenerima = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listPenerimaInAdmin = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        taDeskripsiPenerimaInAdmin = new javax.swing.JTextArea();
        pViewPd = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        listPdInAdmin = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        taDeskripsiPdInAdmin = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredMain.setLayout(new java.awt.CardLayout());

        pLogin.setPreferredSize(new java.awt.Dimension(583, 500));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tfUsername.setToolTipText("Username");

        btnRegister.setText("Register");

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(176, 176, 176))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addGap(388, 388, 388))
        );

        jLayeredMain.add(pLogin, "card2");

        jLabel1.setText("Username");

        jLabel2.setText("No. Telepon");

        jLabel3.setText("Email");

        jLabel4.setText("Password");

        jLabel5.setText("Passwor  Confirmation");

        jLabel6.setText("Account Type");

        jLabel7.setText("---------");

        btnNewRegister.setText("Register");
        btnNewRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRegisterActionPerformed(evt);
            }
        });

        btnCancelRegis.setText("Cancel");

        AccountType.add(rbRegisDonatur);
        rbRegisDonatur.setText("Donatur");
        rbRegisDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegisDonaturActionPerformed(evt);
            }
        });

        AccountType.add(rbRegisPengalangDana);
        rbRegisPengalangDana.setText("Pengalang Dana");

        jLabel32.setText("Nama");

        javax.swing.GroupLayout pRegistrasiLayout = new javax.swing.GroupLayout(pRegistrasi);
        pRegistrasi.setLayout(pRegistrasiLayout);
        pRegistrasiLayout.setHorizontalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRegisName)
                            .addComponent(tfRegisUsername)
                            .addComponent(tfRegisEmail)
                            .addComponent(tfRegisPassword)
                            .addComponent(tfRegisPasswordConfirmation)
                            .addGroup(pRegistrasiLayout.createSequentialGroup()
                                .addComponent(rbRegisDonatur, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbRegisPengalangDana))
                            .addComponent(tfRegisTelp)))
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelRegis)
                        .addGap(109, 109, 109)
                        .addComponent(btnNewRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRegistrasiLayout.setVerticalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfRegisUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRegisName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRegisTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfRegisEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfRegisPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfRegisPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbRegisDonatur)
                    .addComponent(rbRegisPengalangDana))
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRegister)
                    .addComponent(btnCancelRegis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredMain.add(pRegistrasi, "card3");

        pMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pUserinfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Hello ,");

        jLabel9.setText("Username");

        btnEditProfile.setText("Edit Profile");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout pUserinfoLayout = new javax.swing.GroupLayout(pUserinfo);
        pUserinfo.setLayout(pUserinfoLayout);
        pUserinfoLayout.setHorizontalGroup(
            pUserinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(btnEditProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
        );
        pUserinfoLayout.setVerticalGroup(
            pUserinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUserinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(btnEditProfile)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pUserMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pUserMain.setLayout(new java.awt.CardLayout());

        pMainGalangDana.setLayout(new java.awt.CardLayout());

        pMainPengalangDana.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listEventPD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEventPD);

        btnAddEvent.setText("Add Event");

        taDeskripsiPD.setColumns(20);
        taDeskripsiPD.setRows(5);
        jScrollPane2.setViewportView(taDeskripsiPD);

        btnUpdateEvent.setText("Update");

        btnDeleteEvent.setText("Delete");

        jLabel37.setText("List Event");

        jLabel38.setText("Deskripsi Event");

        javax.swing.GroupLayout pMainPengalangDanaLayout = new javax.swing.GroupLayout(pMainPengalangDana);
        pMainPengalangDana.setLayout(pMainPengalangDanaLayout);
        pMainPengalangDanaLayout.setHorizontalGroup(
            pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                        .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                                .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 396, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainPengalangDanaLayout.createSequentialGroup()
                                .addGap(0, 309, Short.MAX_VALUE)
                                .addComponent(btnUpdateEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))
                    .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                        .addComponent(btnAddEvent)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pMainPengalangDanaLayout.setVerticalGroup(
            pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainPengalangDanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMainPengalangDanaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pMainPengalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateEvent)
                            .addComponent(btnDeleteEvent)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddEvent)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pMainGalangDana.add(pMainPengalangDana, "card2");

        jLabel10.setText("Data Penerima :");

        jLabel11.setText("Nama");

        jLabel12.setText("No. Telp");

        jLabel13.setText("Alamat");

        jLabel14.setText("Data Event :");

        jLabel15.setText("Nama Event");

        jLabel16.setText("Tanggal");

        tfTanggalMulaiCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalMulaiCreateActionPerformed(evt);
            }
        });

        jLabel17.setText("-");

        jLabel18.setText("Target Dana");

        jLabel19.setText("Deskripsi");

        PenerimaType.add(rbPersonal);
        rbPersonal.setText("Personal");

        PenerimaType.add(rbLembaga);
        rbLembaga.setText("Lembaga");

        jLabel20.setText("Tipe");

        btnDoneCreateEvent.setText("Create");
        btnDoneCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneCreateEventActionPerformed(evt);
            }
        });

        btnCancelCreateEvent.setText("Cancel");

        javax.swing.GroupLayout pEventCreateLayout = new javax.swing.GroupLayout(pEventCreate);
        pEventCreate.setLayout(pEventCreateLayout);
        pEventCreateLayout.setHorizontalGroup(
            pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventCreateLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEventCreateLayout.createSequentialGroup()
                        .addComponent(tfNamaPenerimaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlamatPenerimaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLembaga)
                    .addComponent(rbPersonal))
                .addGap(184, 184, 184))
            .addGroup(pEventCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(pEventCreateLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescriptionCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTargetDanaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaEventCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pEventCreateLayout.createSequentialGroup()
                                .addComponent(tfTanggalMulaiCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTanggalSelesaiCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventCreateLayout.createSequentialGroup()
                .addComponent(btnCancelCreateEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoneCreateEvent)
                .addContainerGap())
        );
        pEventCreateLayout.setVerticalGroup(
            pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventCreateLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamaPenerimaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rbPersonal)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfAlamatPenerimaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLembaga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfNamaEventCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfTanggalMulaiCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTanggalSelesaiCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTargetDanaCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescriptionCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pEventCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoneCreateEvent)
                    .addComponent(btnCancelCreateEvent)))
        );

        pMainGalangDana.add(pEventCreate, "card3");

        jLabel21.setText("Data Penerima :");

        jLabel22.setText("Nama");

        jLabel23.setText("No. Telp");

        jLabel24.setText("Alamat");

        jLabel25.setText("Data Event :");

        jLabel26.setText("Nama Event");

        jLabel27.setText("Tanggal");

        tfTanggalMulaiUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalMulaiUpdateActionPerformed(evt);
            }
        });

        jLabel28.setText("-");

        jLabel29.setText("Target Dana");

        jLabel30.setText("Deskripsi");

        PenerimaTypeUpdate.add(rbPersonalUpdate);
        rbPersonalUpdate.setSelected(true);
        rbPersonalUpdate.setText("Personal");

        PenerimaTypeUpdate.add(rbLembagaUpdate);
        rbLembagaUpdate.setText("Lembaga");

        jLabel31.setText("Tipe");

        btnDoneUpdateEvent.setText("Update");
        btnDoneUpdateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneUpdateEventActionPerformed(evt);
            }
        });

        btnCancelUpdateEvent.setText("Cancel");

        javax.swing.GroupLayout pEventUpdateLayout = new javax.swing.GroupLayout(pEventUpdate);
        pEventUpdate.setLayout(pEventUpdateLayout);
        pEventUpdateLayout.setHorizontalGroup(
            pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventUpdateLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addGap(33, 33, 33)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEventUpdateLayout.createSequentialGroup()
                        .addComponent(tfNamaPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31))
                    .addComponent(tfTelpPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlamatPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLembagaUpdate)
                    .addComponent(rbPersonalUpdate))
                .addGap(184, 184, 184))
            .addGroup(pEventUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(pEventUpdateLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescriptionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTargetDanaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaEventUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pEventUpdateLayout.createSequentialGroup()
                                .addComponent(tfTanggalMulaiUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTanggalSelesaiUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEventUpdateLayout.createSequentialGroup()
                .addComponent(btnCancelUpdateEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoneUpdateEvent)
                .addContainerGap())
        );
        pEventUpdateLayout.setVerticalGroup(
            pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventUpdateLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamaPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(rbPersonalUpdate)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tfAlamatPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLembagaUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfTelpPenerimaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfNamaEventUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tfTanggalMulaiUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTanggalSelesaiUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTargetDanaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescriptionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pEventUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoneUpdateEvent)
                    .addComponent(btnCancelUpdateEvent)))
        );

        pMainGalangDana.add(pEventUpdate, "card4");

        pUserMain.add(pMainGalangDana, "card3");

        jScrollPane3.setViewportView(listEventDNT);

        jLabel33.setText("List Event Galang Dana");

        taDeskripsiDNT.setColumns(20);
        taDeskripsiDNT.setRows(5);
        jScrollPane4.setViewportView(taDeskripsiDNT);

        jLabel34.setText("Deskripsi Donasi ");

        pPilihanDonatur.setLayout(new java.awt.CardLayout());

        btnMauDonasi.setText("Donasi");
        btnMauDonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauDonasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBelumDonasiLayout = new javax.swing.GroupLayout(pBelumDonasi);
        pBelumDonasi.setLayout(pBelumDonasiLayout);
        pBelumDonasiLayout.setHorizontalGroup(
            pBelumDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBelumDonasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMauDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pBelumDonasiLayout.setVerticalGroup(
            pBelumDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBelumDonasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMauDonasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pPilihanDonatur.add(pBelumDonasi, "card2");

        jLabel35.setText("Input Nominal Donasi :");

        btnKirimDonasi.setText("Kirim");

        btnKembali.setText("Kembali");
        btnKembali.setActionCommand("");

        javax.swing.GroupLayout pDonasiPertamaLayout = new javax.swing.GroupLayout(pDonasiPertama);
        pDonasiPertama.setLayout(pDonasiPertamaLayout);
        pDonasiPertamaLayout.setHorizontalGroup(
            pDonasiPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDonasiPertamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDonasiPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNominalPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDonasiPertamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKirimDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pDonasiPertamaLayout.setVerticalGroup(
            pDonasiPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDonasiPertamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pDonasiPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKirimDonasi)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        pPilihanDonatur.add(pDonasiPertama, "card3");

        jLabel36.setText("Nominal Donasi :");

        btnUpdateDonasi.setText("Update");

        btnBatalDonasi.setText("Batalkan Donasi");

        javax.swing.GroupLayout pIdlePilihanDonasiLayout = new javax.swing.GroupLayout(pIdlePilihanDonasi);
        pIdlePilihanDonasi.setLayout(pIdlePilihanDonasiLayout);
        pIdlePilihanDonasiLayout.setHorizontalGroup(
            pIdlePilihanDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdlePilihanDonasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pIdlePilihanDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pIdlePilihanDonasiLayout.createSequentialGroup()
                        .addGroup(pIdlePilihanDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdleNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pIdlePilihanDonasiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBatalDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pIdlePilihanDonasiLayout.setVerticalGroup(
            pIdlePilihanDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdlePilihanDonasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdleNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pIdlePilihanDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateDonasi)
                    .addComponent(btnBatalDonasi))
                .addContainerGap())
        );

        pPilihanDonatur.add(pIdlePilihanDonasi, "card4");

        javax.swing.GroupLayout pMainDonaturLayout = new javax.swing.GroupLayout(pMainDonatur);
        pMainDonatur.setLayout(pMainDonaturLayout);
        pMainDonaturLayout.setHorizontalGroup(
            pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainDonaturLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(12, 12, 12)
                .addGroup(pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pPilihanDonatur, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pMainDonaturLayout.setVerticalGroup(
            pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainDonaturLayout.createSequentialGroup()
                .addGroup(pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMainDonaturLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainDonaturLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMainDonaturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pMainDonaturLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pPilihanDonatur, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pUserMain.add(pMainDonatur, "card6");

        jLabel40.setText("Nama ");

        jLabel42.setText("No. Telepon");

        jLabel43.setText("Email");

        btnDoneEditProf.setText("Update");
        btnDoneEditProf.setToolTipText("");

        btnCancelEditProf.setText("Cancel");
        btnCancelEditProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEditUserLayout = new javax.swing.GroupLayout(pEditUser);
        pEditUser.setLayout(pEditUserLayout);
        pEditUserLayout.setHorizontalGroup(
            pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelEditProf)
                    .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel40)
                        .addComponent(jLabel42)
                        .addComponent(jLabel43)))
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEditUserLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNewNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEditUserLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoneEditProf)
                        .addGap(56, 56, 56))))
        );
        pEditUserLayout.setVerticalGroup(
            pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditUserLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(29, 29, 29)
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(pEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoneEditProf)
                    .addComponent(btnCancelEditProf))
                .addContainerGap())
        );

        pUserMain.add(pEditUser, "card5");

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUserinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pUserMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pUserinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainLayout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(pUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLayeredMain.add(pMain, "card4");

        jLabel39.setText("Hello Creator ^^");

        btnLogOutAdmin.setText("LogOut");
        btnLogOutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutAdminActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(listEventAdmin);

        taDeskripsiEventAdmin.setColumns(20);
        taDeskripsiEventAdmin.setRows(5);
        jScrollPane8.setViewportView(taDeskripsiEventAdmin);

        jLabel41.setText("Verifikasi :");

        Verifikasi.add(rbVerifTrue);
        rbVerifTrue.setText("Y");
        rbVerifTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerifTrueActionPerformed(evt);
            }
        });

        Verifikasi.add(rbVarifFalse);
        rbVarifFalse.setSelected(true);
        rbVarifFalse.setText("N");

        javax.swing.GroupLayout pVerfikasiLayout = new javax.swing.GroupLayout(pVerfikasi);
        pVerfikasi.setLayout(pVerfikasiLayout);
        pVerfikasiLayout.setHorizontalGroup(
            pVerfikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVerfikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pVerfikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(pVerfikasiLayout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVerifTrue)
                        .addGap(18, 18, 18)
                        .addComponent(rbVarifFalse)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pVerfikasiLayout.setVerticalGroup(
            pVerfikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVerfikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pVerfikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pVerfikasiLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pVerfikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(rbVerifTrue)
                            .addComponent(rbVarifFalse))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Verifikasi Event", pVerfikasi);

        taDeskripsiDtnInAdmin.setColumns(20);
        taDeskripsiDtnInAdmin.setRows(5);
        jScrollPane5.setViewportView(taDeskripsiDtnInAdmin);

        jScrollPane6.setViewportView(listDntInAdmin);

        javax.swing.GroupLayout pViewDntLayout = new javax.swing.GroupLayout(pViewDnt);
        pViewDnt.setLayout(pViewDntLayout);
        pViewDntLayout.setHorizontalGroup(
            pViewDntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pViewDntLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        pViewDntLayout.setVerticalGroup(
            pViewDntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pViewDntLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pViewDntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Donatur", pViewDnt);

        jScrollPane9.setViewportView(listPenerimaInAdmin);

        taDeskripsiPenerimaInAdmin.setColumns(20);
        taDeskripsiPenerimaInAdmin.setRows(5);
        jScrollPane10.setViewportView(taDeskripsiPenerimaInAdmin);

        javax.swing.GroupLayout pViewPenerimaLayout = new javax.swing.GroupLayout(pViewPenerima);
        pViewPenerima.setLayout(pViewPenerimaLayout);
        pViewPenerimaLayout.setHorizontalGroup(
            pViewPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pViewPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pViewPenerimaLayout.setVerticalGroup(
            pViewPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pViewPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pViewPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(pViewPenerimaLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Penerima", pViewPenerima);

        jScrollPane11.setViewportView(listPdInAdmin);

        taDeskripsiPdInAdmin.setColumns(20);
        taDeskripsiPdInAdmin.setRows(5);
        jScrollPane12.setViewportView(taDeskripsiPdInAdmin);

        javax.swing.GroupLayout pViewPdLayout = new javax.swing.GroupLayout(pViewPd);
        pViewPd.setLayout(pViewPdLayout);
        pViewPdLayout.setHorizontalGroup(
            pViewPdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pViewPdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12)
                .addContainerGap())
        );
        pViewPdLayout.setVerticalGroup(
            pViewPdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pViewPdLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pViewPdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(pViewPdLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Pengalang Dana", pViewPd);

        javax.swing.GroupLayout pAdminLayout = new javax.swing.GroupLayout(pAdmin);
        pAdmin.setLayout(pAdminLayout);
        pAdminLayout.setHorizontalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAdminLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(pAdminLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        pAdminLayout.setVerticalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdminLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(btnLogOutAdmin))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredMain.add(pAdmin, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredMain, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewRegisterActionPerformed

    private void rbRegisDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegisDonaturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRegisDonaturActionPerformed

    private void tfTanggalMulaiCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalMulaiCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalMulaiCreateActionPerformed

    private void btnDoneCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneCreateEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneCreateEventActionPerformed

    private void tfTanggalMulaiUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalMulaiUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalMulaiUpdateActionPerformed

    private void btnDoneUpdateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneUpdateEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneUpdateEventActionPerformed

    private void btnMauDonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauDonasiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnMauDonasiActionPerformed

    private void btnLogOutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutAdminActionPerformed

    private void rbVerifTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerifTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVerifTrueActionPerformed

    private void btnCancelEditProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelEditProfActionPerformed

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JButton getBtnRegister() {
        return btnRegister;
    }

    public JButton getBtnCancelRegis() {
        return btnCancelRegis;
    }

    public JButton getBtnNewRegister() {
        return btnNewRegister;
    }

    public JButton getBtnEditProfile() {
        return btnEditProfile;
    }

    public JButton getBtnBatalDonasi() {
        return btnBatalDonasi;
    }

    public JButton getBtnDeleteEvent() {
        return btnDeleteEvent;
    }

    public JButton getBtnKirimDonasi() {
        return btnKirimDonasi;
    }

    public JButton getBtnLogOutAdmin() {
        return btnLogOutAdmin;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnMauDonasi() {
        return btnMauDonasi;
    }

    public JButton getBtnUpdateDonasi() {
        return btnUpdateDonasi;
    }
    
    public JButton getBtnUpdateEvent() {
        return btnUpdateEvent;
    }

    public JButton getBtnCancelEditProf() {
        return btnCancelEditProf;
    }

    public JButton getBtnDoneEditProf() {
        return btnDoneEditProf;
    }

    public JButton getBtnAddEvent() {
        return btnAddEvent;
    }

    public JButton getBtnCancelCreateEvent() {
        return btnCancelCreateEvent;
    }

    public JButton getBtnDoneCreateEvent() {
        return btnDoneCreateEvent;
    }

    public JButton getBtnCancelUpdateEvent() {
        return btnCancelUpdateEvent;
    }

    public JButton getBtnDoneUpdateEvent() {
        return btnDoneUpdateEvent;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }
    
    public JRadioButton getRbLembaga() {
        return rbLembaga;
    }
    
    public JRadioButton getRbLembagaUpdate() {
        return rbLembagaUpdate;
    }

    public JRadioButton getRbPersonal() {
        return rbPersonal;
    }
    
    public JRadioButton getRbPersonalUpdate() {
        return rbPersonalUpdate;
    }
    
    public JRadioButton getRbRegisDonatur() {
        return rbRegisDonatur;
    }
    
    public JRadioButton getRbRegisPengalangDana() {
        return rbRegisPengalangDana;
    }
    
    public JRadioButton getRbVarifFalse() {
        return rbVarifFalse;
    }
    
    public JRadioButton getRbVarifTrue() {
        return rbVerifTrue;
    }
    
    
    
    
    
    public void addActionListener(ActionListener al) {
        btnBatalDonasi.addActionListener(al);
        btnCancelRegis.addActionListener(al);
        btnDeleteEvent.addActionListener(al);
        btnEditProfile.addActionListener(al);
        btnKembali.addActionListener(al);
        btnKirimDonasi.addActionListener(al);
        btnLogOutAdmin.addActionListener(al);
        btnLogin.addActionListener(al);
        btnLogout.addActionListener(al);
        btnMauDonasi.addActionListener(al);
        btnNewRegister.addActionListener(al);
        btnRegister.addActionListener(al);
        btnUpdateDonasi.addActionListener(al);
        btnUpdateEvent.addActionListener(al);
        btnCancelEditProf.addActionListener(al);
        btnDoneEditProf.addActionListener(al);
        btnAddEvent.addActionListener(al);
        btnDoneCreateEvent.addActionListener(al);
        btnCancelCreateEvent.addActionListener(al);
        btnDoneUpdateEvent.addActionListener(al);
        btnCancelUpdateEvent.addActionListener(al);        
        btnKembali.addActionListener(al);
    }
    
    public JList getListDntInAdmin() {
        return listDntInAdmin;
    }
    
    public int getSelectedDntInAdmin() {
        return listDntInAdmin.getSelectedIndex();
    }
    
    public JList getListEventAdmin() {
        return listEventAdmin;
    }
    
    public int getSelectedEventAdmin() {
        return listEventAdmin.getSelectedIndex();
    }
    
    public JList getListEventDNT() {
        return listEventDNT;
    }
    
    public int getSelectedEventDNT() {
        return listEventDNT.getSelectedIndex();
    }
    
    public JList getListEventPD() {
        return listEventPD;
    }
    
    public int getSelectedEventPD() {
        return listEventPD.getSelectedIndex();
    }
    
    public JList getListPdInAdmin() {
        return listPdInAdmin;
    }
    
    public int getSelectedPdInAdmin() {
        return listPdInAdmin.getSelectedIndex();
    }
    
    public JList getListPenerimaAdmin() {
        return listPenerimaInAdmin;
    }
    
    public int getSelectedPenerimaInAdmin() {
        return listPenerimaInAdmin.getSelectedIndex();
    }
    
    public void addMouseAdaper(MouseAdapter ma) {
        listDntInAdmin.addMouseListener(ma);
        listEventAdmin.addMouseListener(ma);
        listEventDNT.addMouseListener(ma);
        listEventPD.addMouseListener(ma);
        listPdInAdmin.addMouseListener(ma);
        listPenerimaInAdmin.addMouseListener(ma);
    }
    
    public JPanel getPAdmin() {
        return pAdmin;
    }
    
    public JPanel getPBelumDonasi() {
        return pBelumDonasi;
    }
    
    public JPanel getPDonasiPertama() {
        return pDonasiPertama;
    }        
    
    public JPanel getPEditUser() {
        return pEditUser;
    }
    
    public JPanel getPEventUpdate() {
        return pEventUpdate;
    }

    public JPanel getPEventCreate() {
        return pEventCreate;
    }
        
    
    public JPanel getPIdlePilihanDonasi() {
        return pIdlePilihanDonasi;
    }
    
    public JPanel getPLogin() {
        return pLogin;
    }
    
    public JPanel getPMain() {
        return pMain;
    }
    
    public JPanel getPMainDonatur() {
        return pMainDonatur;
    }
    
    public JPanel getPMainGalangDana() {
        return pMainGalangDana;
    }
    
    public JPanel getPMainPenggalangDana() {
        return pMainPengalangDana;
    }
    
    public JPanel getPPilihanDonatur() {
        return pPilihanDonatur;
    }
    
    public JPanel getPRegistrasi() {
        return pRegistrasi;
    }
    
    public JPanel getPUserMain() {
        return pUserMain;
    }
    
    public JPanel getPUserInfo() {
        return pUserinfo;
    }
    
    public JPanel getPVerifikasi() {
        return pVerfikasi;
    }
    
    public JPanel getPViewDnt() {
        return pViewDnt;
    }
    
    public JPanel getPViewPd() {
        return pViewPd;
    }
    
    public JPanel getPViewPenerima() {
        return pViewPenerima;
    }

    public JLayeredPane getjLayeredMain() {
        return jLayeredMain;
    }

    
    
    
    
    
    public void switcPanel(JLayeredPane j, JPanel p){
        j.removeAll();
        j.add(p);
        j.repaint();
        j.revalidate();
    }
    
    public void switcPanel(JPanel j, JPanel p){
        j.removeAll();
        j.add(p);
        j.repaint();
        j.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AccountType;
    private javax.swing.ButtonGroup PenerimaType;
    private javax.swing.ButtonGroup PenerimaTypeUpdate;
    private javax.swing.ButtonGroup Verifikasi;
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnBatalDonasi;
    private javax.swing.JButton btnCancelCreateEvent;
    private javax.swing.JButton btnCancelEditProf;
    private javax.swing.JButton btnCancelRegis;
    private javax.swing.JButton btnCancelUpdateEvent;
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnDoneCreateEvent;
    private javax.swing.JButton btnDoneEditProf;
    private javax.swing.JButton btnDoneUpdateEvent;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKirimDonasi;
    private javax.swing.JButton btnLogOutAdmin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMauDonasi;
    private javax.swing.JButton btnNewRegister;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdateDonasi;
    private javax.swing.JButton btnUpdateEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JList<String> listDntInAdmin;
    private javax.swing.JList<String> listEventAdmin;
    private javax.swing.JList<String> listEventDNT;
    private javax.swing.JList<String> listEventPD;
    private javax.swing.JList<String> listPdInAdmin;
    private javax.swing.JList<String> listPenerimaInAdmin;
    private javax.swing.JPanel pAdmin;
    private javax.swing.JPanel pBelumDonasi;
    private javax.swing.JPanel pDonasiPertama;
    private javax.swing.JPanel pEditUser;
    private javax.swing.JPanel pEventCreate;
    private javax.swing.JPanel pEventUpdate;
    private javax.swing.JPanel pIdlePilihanDonasi;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pMainDonatur;
    private javax.swing.JPanel pMainGalangDana;
    private javax.swing.JPanel pMainPengalangDana;
    private javax.swing.JPanel pPilihanDonatur;
    private javax.swing.JPanel pRegistrasi;
    private javax.swing.JPanel pUserMain;
    private javax.swing.JPanel pUserinfo;
    private javax.swing.JPanel pVerfikasi;
    private javax.swing.JPanel pViewDnt;
    private javax.swing.JPanel pViewPd;
    private javax.swing.JPanel pViewPenerima;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JRadioButton rbLembaga;
    private javax.swing.JRadioButton rbLembagaUpdate;
    private javax.swing.JRadioButton rbPersonal;
    private javax.swing.JRadioButton rbPersonalUpdate;
    private javax.swing.JRadioButton rbRegisDonatur;
    private javax.swing.JRadioButton rbRegisPengalangDana;
    private javax.swing.JRadioButton rbVarifFalse;
    private javax.swing.JRadioButton rbVerifTrue;
    private javax.swing.JTextArea taDeskripsiDNT;
    private javax.swing.JTextArea taDeskripsiDtnInAdmin;
    private javax.swing.JTextArea taDeskripsiEventAdmin;
    private javax.swing.JTextArea taDeskripsiPD;
    private javax.swing.JTextArea taDeskripsiPdInAdmin;
    private javax.swing.JTextArea taDeskripsiPenerimaInAdmin;
    private javax.swing.JTextField tfAlamatPenerimaCreate;
    private javax.swing.JTextField tfAlamatPenerimaUpdate;
    private javax.swing.JTextField tfDescriptionCreate;
    private javax.swing.JTextField tfDescriptionUpdate;
    private javax.swing.JTextField tfIdleNominal;
    private javax.swing.JTextField tfNamaEventCreate;
    private javax.swing.JTextField tfNamaEventUpdate;
    private javax.swing.JTextField tfNamaPenerimaCreate;
    private javax.swing.JTextField tfNamaPenerimaUpdate;
    private javax.swing.JTextField tfNewEmail;
    private javax.swing.JTextField tfNewName;
    private javax.swing.JTextField tfNewNoTelp;
    private javax.swing.JTextField tfNominalPertama;
    private javax.swing.JTextField tfRegisEmail;
    private javax.swing.JTextField tfRegisName;
    private javax.swing.JTextField tfRegisPassword;
    private javax.swing.JTextField tfRegisPasswordConfirmation;
    private javax.swing.JTextField tfRegisTelp;
    private javax.swing.JTextField tfRegisUsername;
    private javax.swing.JTextField tfTanggalMulaiCreate;
    private javax.swing.JTextField tfTanggalMulaiUpdate;
    private javax.swing.JTextField tfTanggalSelesaiCreate;
    private javax.swing.JTextField tfTanggalSelesaiUpdate;
    private javax.swing.JTextField tfTargetDanaCreate;
    private javax.swing.JTextField tfTargetDanaUpdate;
    private javax.swing.JTextField tfTelpPenerimaUpdate;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
